### ISSUE TITLE
Linux Flavor?

### ISSUE THREAD

**Issue by IshanArya** [zachw000/KissanimeAPI#1]
Sorry, I didn't know how else to contact you. Can you please tell me what Linux distro you are using in the screenshot? It looks really nice.

**Comment by zachw000** [comment]
Thanks! I am using OpenSUSE w/KDE in the screenshot! :) I am currently trying to re-write the code because Kissanime has circumvented my authentication code, and I am also working on porting the code so that it would work on non UNIX/Linux based OS's.

**Comment by IshanArya** [comment]
Can it already work on non-Linux OS's because you wrote it in Node.js?

**Comment by zachw000** [comment]
I have noticed some problems on non-Linux OS's, I honestly have no clue why, and I have filed it as a bug report to Node.js, this is mostly in the cookie store and request functions, so in the state the Github branch is in, this code does not work on non-Linux/UNIX OS's. Besides that, it should work fine assuming all the plugins necessary are loaded.
